apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opendota-ml-pipeline-ingress-canary
  labels:
    app: opendota-ml-pipeline
    track: canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: opendota.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opendota-ml-pipeline-canary
            port:
              number: 80
